//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLViewRibbon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTLViewRibbon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear current project.
        /// </summary>
        public static string ButtonClearCurrent {
            get {
                return ResourceManager.GetString("ButtonClearCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTypes.
        /// </summary>
        public static string ButtonErrorTypes {
            get {
                return ResourceManager.GetString("ButtonErrorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate project.
        /// </summary>
        public static string ButtonEstimation {
            get {
                return ResourceManager.GetString("ButtonEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPlan.
        /// </summary>
        public static string ButtonNewPlan {
            get {
                return ResourceManager.GetString("ButtonNewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveData.
        /// </summary>
        public static string ButtonSaveData {
            get {
                return ResourceManager.GetString("ButtonSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techniques.
        /// </summary>
        public static string ButtonTechniques {
            get {
                return ResourceManager.GetString("ButtonTechniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct cost:.
        /// </summary>
        public static string DirectCost {
            get {
                return ResourceManager.GetString("DirectCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution of defect types:.
        /// </summary>
        public static string DistributionDefect {
            get {
                return ResourceManager.GetString("DistributionDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future cost:.
        /// </summary>
        public static string FutureCost {
            get {
                return ResourceManager.GetString("FutureCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error types and Techniques.
        /// </summary>
        public static string GBErrorTypeAndTechnique {
            get {
                return ResourceManager.GetString("GBErrorTypeAndTechnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string GBInformation {
            get {
                return ResourceManager.GetString("GBInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string GBParameter {
            get {
                return ResourceManager.GetString("GBParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string GBPlan {
            get {
                return ResourceManager.GetString("GBPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string GBResult {
            get {
                return ResourceManager.GetString("GBResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string GroupEstimation {
            get {
                return ResourceManager.GetString("GroupEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string GroupLanguage {
            get {
                return ResourceManager.GetString("GroupLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string GroupManager {
            get {
                return ResourceManager.GetString("GroupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labor cost:.
        /// </summary>
        public static string LaborCost {
            get {
                return ResourceManager.GetString("LaborCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Error Types.
        /// </summary>
        public static string ListErrorTypes {
            get {
                return ResourceManager.GetString("ListErrorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Techniques.
        /// </summary>
        public static string ListTechniques {
            get {
                return ResourceManager.GetString("ListTechniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of errors:.
        /// </summary>
        public static string NumberOfErrors {
            get {
                return ResourceManager.GetString("NumberOfErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit:.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue:.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI:.
        /// </summary>
        public static string ROI {
            get {
                return ResourceManager.GetString("ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTL_KTCNPM.
        /// </summary>
        public static string TitleMainWindow {
            get {
                return ResourceManager.GetString("TitleMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost:.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
    }
}
